// The imported level JSON, loaded through aa_data, reproduces the decrypted plists bit for bit
// (tests/expected_levels.inc, generated by tools/gen_level_expectations.py).
#include "aa/data/level_loader.h"
#include "aa/sim/float_bits.h"
#include "test_support.h"

#include <doctest.h>

#include <cstdint>
#include <limits>
#include <string>

namespace {

struct ExpectedItem {
    int type;
    int handle;
    std::uint32_t cx, cy, angle;
    int flags;
    std::uint32_t ropeX, ropeY;
    int itemData;
    int attachmentCount;
};

struct ExpectedLevel {
    const char* chapter;
    const char* name;
    int sourceVersion;
    int backgroundIndex;
    int toolboxCount;
    int itemCount;
    const ExpectedItem* items;
    int goalType;
    int goalItemCount;
    int goalHandle0, goalHandle2_0;
    std::uint32_t goalHeight, goalWidth, goalAngle;
};

#include "expected_levels.inc"

}  // namespace

TEST_CASE("level loader: shipped levels round-trip bit for bit") {
    AA_REQUIRE_ASSETS();
    using aa::sim::bitsFromFloat;
    for (const ExpectedLevel& e : kExpectedLevels) {
        const std::string path = assetsDir() + "/levels/" + e.chapter + "/" + e.name + ".json";
        INFO(path);
        const aa::sim::Level level = aa::data::loadLevelFile(path);
        CHECK(level.version == 7);
        CHECK(level.backgroundIndex == e.backgroundIndex);
        CHECK(static_cast<int>(level.toolbox.size()) == e.toolboxCount);
        REQUIRE(static_cast<int>(level.items.size()) == e.itemCount);
        for (int i = 0; i < e.itemCount; ++i) {
            INFO("item " << i);
            const aa::sim::LevelItem& it = level.items[static_cast<std::size_t>(i)];
            const ExpectedItem& x = e.items[i];
            CHECK(static_cast<int>(it.type) == x.type);
            CHECK(it.handle == x.handle);
            CHECK(bitsFromFloat(it.center.x) == x.cx);
            CHECK(bitsFromFloat(it.center.y) == x.cy);
            CHECK(bitsFromFloat(it.angle) == x.angle);
            CHECK(it.flags == x.flags);
            CHECK(bitsFromFloat(it.ropeEnd.x) == x.ropeX);
            CHECK(bitsFromFloat(it.ropeEnd.y) == x.ropeY);
            CHECK(it.itemData == x.itemData);
            CHECK(it.attachmentCount == x.attachmentCount);
            CHECK(aa::sim::Handle::typeOf(it.handle) == it.type);
        }
        CHECK(level.goal.type == e.goalType);
        CHECK(level.goal.itemCount == e.goalItemCount);
        CHECK(level.goal.itemHandles[0] == e.goalHandle0);
        CHECK(level.goal.itemHandles2[0] == e.goalHandle2_0);
        CHECK(bitsFromFloat(level.goal.height) == e.goalHeight);
        CHECK(bitsFromFloat(level.goal.width) == e.goalWidth);
        CHECK(bitsFromFloat(level.goal.angle) == e.goalAngle);
    }
}

TEST_CASE("level loader: legacy type 40 was converted by the importer") {
    AA_REQUIRE_ASSETS();
    const aa::sim::Level level = aa::data::loadLevelFile(assetsDir() + "/levels/03_Treehouse/Helipad.json");
    bool helicopter = false;
    for (const aa::sim::LevelItem& it : level.items) {
        CHECK(it.type != aa::sim::ItemType::SelectionArea);
        if (it.type == aa::sim::ItemType::Helicopter) {
            helicopter = true;
            CHECK(aa::sim::Handle::typeOf(it.itemData) == aa::sim::ItemType::RCController);
        }
    }
    CHECK(helicopter);
}

TEST_CASE("level loader: chapter index") {
    AA_REQUIRE_ASSETS();
    const aa::data::LevelIndex index = aa::data::loadLevelIndexFile(assetsDir() + "/levels/00_Classroom/index.json");
    CHECK(index.name == "CHAPTER_NAME_CHAPTER1");
    REQUIRE(index.levels.size() == 16);
    CHECK(index.levels.front() == "Playtime");
    CHECK(index.levels.back() == "CatchBalloon");
}

TEST_CASE("json: integers are range-checked, not wrapped") {
    const aa::data::JsonDoc doc("{\"a\": 4294967295, \"b\": 1.5, \"c\": -2147483648, \"d\": 1e300}", "inline");
    CHECK_THROWS_AS(doc.root().child("a").getInt(), aa::data::JsonError);
    CHECK_THROWS_AS(doc.root().child("b").getInt(), aa::data::JsonError);
    CHECK_THROWS_AS(doc.root().child("d").getInt(), aa::data::JsonError);
    CHECK(doc.root().child("c").getInt() == std::numeric_limits<int>::min());
}

TEST_CASE("level loader: rejects a wrong version") {
    const aa::data::JsonDoc doc("{\"version\": 6}", "inline");
    CHECK_THROWS_AS(aa::data::loadLevel(doc.root()), aa::data::JsonError);
}
