#!/usr/bin/env python3
"""Generate docs/07-levels-catalog.md from decrypted level plists + localisation JSON."""
from __future__ import annotations

import argparse
import json
import plistlib
import sys
from collections import Counter
from pathlib import Path

ITEM_NAMES = {
    1: "Shelf", 2: "TennisBall", 3: "BowlingBall", 4: "SoccerBall", 5: "Balloon", 6: "Scissors",
    7: "Bucket", 8: "Hook", 9: "Rope", 10: "CardboardBoxMedium", 11: "CardboardBoxSmall",
    12: "FishBowl", 13: "PiggyBank", 14: "BoxingGlove", 15: "Book", 16: "EightBall", 17: "Pipe",
    18: "Pipe90", 19: "Doll", 20: "Skateboard", 21: "Pulley", 22: "Seesaw", 23: "GoalStar",
    24: "Billboard", 25: "Magnet", 26: "Pinball", 27: "PaperPlane", 28: "Spring", 29: "Dart",
    30: "HangingLamp", 31: "WorldBound", 32: "LaundryBasket", 33: "Bumper", 34: "Slingshot",
    35: "RCTruck", 36: "RCController", 37: "Trapdoor", 38: "TrapdoorLever", 39: "Helicopter",
    40: "RCHelicopterController", 41: "BouncyBall", 42: "ZipLine",
}
GOAL_NAMES = {
    2: "Touch (item1 ↔ item2)", 3: "Item on floor", 4: "(never)", 5: "Item activated (popped/broken)",
    6: "Item above y", 7: "Item inside container ≥0.3 s", 8: "Item below y", 9: "Item right of x",
    10: "Item left of x",
}
CHAPTERS = ["00_Classroom", "01_Backyard", "02_Room", "03_Treehouse"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("levels_dir", type=Path)
    ap.add_argument("texts_json", type=Path)
    ap.add_argument("out", type=Path)
    args = ap.parse_args()
    texts = json.load(args.texts_json.open(encoding="utf-8"))["en_EN"]

    lines = ["# Level catalogue (generated by `tools/gen_levels_catalog.py`)", "",
             "Source: `Levels/<chapter>/0_Location.plist` (order) + `<Level>.plist`. "
             "Type 40 `RCHelicopterController` is a legacy id that the loader converts to `RCController` (02 §5). "
             "Names/tips from `TEXTS_BASIC.dat` (en_EN). Coordinates in metres, world 3.41 × 2.12 m. "
             "Item counts exclude WorldBound and stars (★ = star count).", ""]
    for ch_idx, ch in enumerate(CHAPTERS):
        loc = plistlib.load((args.levels_dir / ch / "0_Location.plist").open("rb"))
        lines.append(f"## {ch} — {texts.get(loc['name'], loc['name'])} (`{loc['name']}`)")
        lines.append("")
        lines.append("| # | File | Title | Ver | Bg | Goal | Pre-placed items | Toolbox | Tip |")
        lines.append("|---|------|----------|--------|-----|------|------------------|---------|-----------|")
        for i, name in enumerate(loc["levels"], 1):
            lv = plistlib.load((args.levels_dir / ch / f"{name}.plist").open("rb"))
            items = [lv[f"itemInfos_{k}"] for k in range(lv["itemCount"])]
            counts = Counter(ITEM_NAMES.get(it["type"], str(it["type"])) for it in items if it["type"] not in (31, 23))
            stars = sum(1 for it in items if it["type"] == 23)
            item_str = ", ".join(f"{n}×{c}" if c > 1 else n for n, c in sorted(counts.items()))
            tb = ", ".join(
                f"{ITEM_NAMES.get(lv[f'toolboxSlots_{s}']['type'], lv[f'toolboxSlots_{s}']['type'])}×{lv[f'toolboxSlots_{s}']['amount']}"
                for s in range(lv["toolboxSlotCount"]))
            g = lv["goal"]
            handles = {it["handle"]: it["type"] for it in items}
            n = g["itemCount"]
            targets = ", ".join(ITEM_NAMES.get(handles.get(h, -1), "?") for h in g["itemHandles"][:n])
            goal = f"{g['type']} {GOAL_NAMES.get(g['type'], '?')}: {targets}"
            if g["type"] in (6, 8):
                goal += f" (y={g['height']:.2f})"
            elif g["type"] in (9, 10):
                goal += f" (x={g['width']:.2f})"
            elif g["type"] in (2, 7):
                goal += " → " + ", ".join(ITEM_NAMES.get(handles.get(h, -1), "?") for h in g["itemHandles2"][:n])
            if g["negated"]:
                goal += " [negated]"
            title = texts.get(lv["title"], lv["title"])
            tip = texts.get(lv["description"], lv["description"]).replace("|", "\\|")
            lines.append(f"| {i} | `{name}` | {title} | {lv['version']} | {lv['backgroundIndex']} | {goal} | "
                         f"{item_str} (★{stars}) | {tb or '—'} | {tip} |")
        lines.append("")
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
