#!/usr/bin/env python3
"""Generate core/third_party/aa_libm/kat.inc, the known-answer table for aa_libm_selftest.

Inputs: fixed special values (0, ±tiny, ±π multiples, limits) plus deterministic pseudo-random values in
the ranges the game uses; outputs are recorded from the vendored library built on this machine
(tools/uc_harness.load_aa_libm), i.e. the platform the physics harness certified. Run once on the
reference platform; other platforms only run the self-test.

Usage: gen_aa_libm_kat.py [--per-func 200]
"""
from __future__ import annotations

import argparse
import logging
import math
import random
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from uc_harness import AA_LIBM_FUNCS, load_aa_libm  # noqa: E402

log = logging.getLogger("gen_aa_libm_kat")
OUT = Path(__file__).resolve().parent.parent / "core/third_party/aa_libm/kat.inc"
SPECIAL = (0.0, -0.0, 1e-300, -1e-300, 5e-324, 1e-9, 0.5, 1.0, -1.0, 2.0, 0.1, math.pi, -math.pi, math.pi / 2,
           math.pi / 4, 3 * math.pi / 2, 2 * math.pi, 10.0, 100.0, 709.0, -745.0, 1e10, 1e22, 2.0 ** 52, float("inf"),
           -float("inf"), float("nan"))
RANGES = {   # per function: sampling range for the first (and second) argument
    "sin": (-64, 64), "cos": (-64, 64), "tan": (-64, 64), "asin": (-1, 1), "acos": (-1, 1), "atan": (-100, 100),
    "atan2": (-100, 100), "exp": (-40, 40), "expm1": (-40, 40), "log": (1e-6, 1e6), "log10": (1e-6, 1e6),
    "pow": (1e-3, 100), "sinh": (-30, 30), "cosh": (-30, 30), "tanh": (-30, 30),
}
POW_EXP = (-4, 4)


def bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--per-func", type=int, default=200)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    rng = random.Random(20120712)   # fixed seed: the table is reproducible
    funcs = load_aa_libm()
    lines = []
    for name, fn in funcs.items():
        arity = AA_LIBM_FUNCS[name]
        lo, hi = RANGES[name]
        inputs: list[tuple[float, float]] = []
        for s in SPECIAL:
            inputs.append((s, 1.0) if name == "atan2" else (s, 0.5 if name == "pow" else 0.0))
        for _ in range(args.per_func):
            a = rng.uniform(lo, hi)
            b = rng.uniform(*POW_EXP) if name == "pow" else rng.uniform(lo, hi)
            inputs.append((a, b))
        for a, b in inputs:
            r = fn(a, b) if arity == 2 else fn(a)
            lines.append(f'    {{"{name}", 0x{bits(a):016x}ull, 0x{bits(b):016x}ull, 0x{bits(r):016x}ull}},')
    OUT.write_text("/* generated by tools/gen_aa_libm_kat.py; do not edit */\n" + "\n".join(lines) + "\n",
                   encoding="utf-8")
    log.info("wrote %s (%d cases)", OUT, len(lines))


if __name__ == "__main__":
    main()
