#!/usr/bin/env python3
"""Generate tests/expected_levels.inc: the float32 bit patterns and integer fields of a few shipped levels,
read directly from the decrypted plists with the original's parse path (strtod → double → float32,
docs/02-level-format.md §6). tests/test_level_loader.cpp compares the imported JSON, loaded through aa_data,
against these values bit for bit — closing the importer → cJSON → (float) round trip on real data.

Usage: gen_level_expectations.py extracted/ios_dec/Levels tests/expected_levels.inc [chapter/Name ...]
"""
from __future__ import annotations

import argparse
import logging
import plistlib
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from import_assets import convert_level  # noqa: E402  (the same normalisation the importer applies)

log = logging.getLogger("gen_level_expectations")

# Representative levels: the first level, a legacy version-6 level with the type-40 conversion, a rope
# level with attachments, a flipped/rotated-heavy level and one hidden Treehouse level.
DEFAULT_LEVELS = ["00_Classroom/Playtime", "03_Treehouse/Helipad", "01_Backyard/SlamDunk", "02_Room/DangerRoad",
                  "03_Treehouse/HoneyBucket", "02_Room/BumperFun"]


def bits(x: float) -> str:
    return "0x%08xu" % struct.unpack("<I", struct.pack("<f", x))[0]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("levels_dir", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("levels", nargs="*", default=DEFAULT_LEVELS, help="chapter/Name (default: a representative set)")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    out = ["// Generated by tools/gen_level_expectations.py from the decrypted level plists — do not edit.",
           "// Floats are float32 bit patterns; see tests/test_level_loader.cpp.", ""]
    entries = []
    for ref in args.levels:
        chapter, name = ref.split("/")
        rel = f"Levels/{chapter}/{name}.plist"
        with (args.levels_dir / chapter / f"{name}.plist").open("rb") as fh:
            level = convert_level(plistlib.load(fh), rel)
        ident = f"{chapter}_{name}".replace("-", "_")
        out.append(f"static const ExpectedItem kItems_{ident}[] = {{")
        for it in level["items"]:
            out.append(f"    {{{it['type']}, {it['handle']}, {bits(it['center'][0])}, {bits(it['center'][1])}, "
                       f"{bits(it['angle'])}, {it['flags']}, {bits(it['ropeEnd'][0])}, {bits(it['ropeEnd'][1])}, "
                       f"{it['itemData']}, {len(it['attachments'])}}},")
        out.append("};")
        g = level["goal"]
        entries.append(f'    {{"{chapter}", "{name}", {level["sourceVersion"]}, {level["backgroundIndex"]}, '
                       f'{len(level["toolbox"])}, {len(level["items"])}, kItems_{ident}, {g["type"]}, {g["itemCount"]}, '
                       f'{g["itemHandles"][0]}, {g["itemHandles2"][0]}, {bits(g["height"])}, {bits(g["width"])}, '
                       f'{bits(g["angle"])}}},')
        log.info("%s: %d items", ref, len(level["items"]))
    out.append("")
    out.append("static const ExpectedLevel kExpectedLevels[] = {")
    out += entries
    out.append("};")
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    log.info("wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
